### ISSUE TITLE
Precious Metal not Transferring. 

### ISSUE THREAD

**Issue by Unikatze** [Doctor-Unspeakable/foundry-pathbuilder2e-import#1]
Hi, 

I just imported a character sheet. And he had a +1 Low Grade Silver Longsword. 
The +1 Potency rune transferred over just fine, but the Silver did not. 

I also assume the names not changing has something to do with the way the compendium is set up in Foundry and that not much can be done about that. 

(On a separate note, is it possible for things to remain in their designated containers?)

Thanks for all your work!

**Comment by mirkoRainer** [comment]
RE: Separate note:
Foundry doesn't support unexploded kits, I imagine this is why containers don't persist.

https://github.com/Doctor-Unspeakable/foundry-pathbuilder2e-import/blob/dc0a0e588c39be978441d1e2725a71c81b981e78/pathbuilder-import.js#L333

**Comment by Unikatze** [comment]
> RE: Separate note:
> Foundry doesn't support unexploded kits, I imagine this is why containers don't persist.
> 
> https://github.com/Doctor-Unspeakable/foundry-pathbuilder2e-import/blob/dc0a0e588c39be978441d1e2725a71c81b981e78/pathbuilder-import.js#L333

Not just kits though. Pathbuilder, much like Foundry, allows you to show what container an item is in. 
So for example if you have a Bandolier, You can set it as a container and specify that, for example,  your dagger, your healer's Kit and your Potion of Healing are in your Bandolier, 

![image](https://user-images.githubusercontent.com/43307189/94718315-97c3e780-031f-11eb-9eeb-025c1e2619d4.png)
![image](https://user-images.githubusercontent.com/43307189/94718758-2d5f7700-0320-11eb-8ca0-a1ecbfc83c59.png)

**Comment by Doctor-Unspeakable** [comment]
OK a couple of issues here.  Please try to separate into different issues if possible next time so I can close each issue separately.

1) I've added import of weapon material.  Basically forgot about it.  While I was doing that I noticed that foundry property runes are stored in camelCase not lowercase so I fixed that too.

2) I've set the display names of weapons as they appear in pathbuilder to transfer across.

3) Keeping things in containers isn't possible as there is a fundamentally different way that pathbuilder and foundry use containers (in pathbuilder they are just containers, not item-container hybrids like foundry). I kind of suspect that after a level 1 import, people will be unchecking the import equipment anyway since you're more likely to be gaining gear in-game during sessions.
