### ISSUE TITLE
Weapons with class/character specific proficiencies prevent full import in FVTT 8.6.0

### ISSUE THREAD

**Issue by IAmAnAzgul** [Doctor-Unspeakable/foundry-pathbuilder2e-import#24]
Example: A Bard character that is proficient in Rapier, but not in martial weapons will not complete the import process if they have a rapier ANYWHERE in their inventory in the Pathbuilder app. Tried this with Shortbow and Kukri while having Gnome weapon familiarity, all froze the import process before class, ancestry, inventory, and feats were imported.

**Comment by Doctor-Unspeakable** [comment]
They changed the way specific proficiencies work, and foundry now automatically adds class specific proficiencies.

I've disabled the code in the import module that attempted to add specific proficiencies, so some may need to be added manually, since I can't see a way to interface with their new system.
